from __future__ import annotations

from decimal import Decimal
from typing import Any, Protocol


class CashFlowRepositoryPort(Protocol):
    def latest_invoice_month(self) -> str | None: ...

    def create_card_forecast(self, month: str, description: str, amount: Decimal, category_slug: str) -> dict[str, Any] | None: ...

    def list_card_forecasts(self, month: str | None, limit: int) -> list[dict[str, Any]]: ...

    def remove_card_forecast(self, forecast_id: int) -> bool: ...

    def create_expense(self, month: str, description: str, amount: Decimal, category_slug: str, payment_method: str, expense_type: str, recurrence_mode: str, recurrence_end_month: str | None) -> dict[str, Any]: ...

    def list_expenses(self, month: str | None, limit: int) -> list[dict[str, Any]]: ...

    def update_expense(self, expense_id: int, month: str, description: str, amount: Decimal, category_slug: str, payment_method: str, expense_type: str, recurrence_mode: str, recurrence_end_month: str | None) -> dict[str, Any] | str: ...

    def remove_expense(self, expense_id: int) -> bool: ...

    def set_expense_recurrence(self, expense_id: int, mode: str, end_month: str | None) -> str: ...

    def get_monthly_summary(self, month: str, include_manual: bool = True) -> dict[str, Any]: ...

    def save_monthly_summary(self, month: str, income: Decimal, saved_base: Decimal) -> dict[str, Any]: ...

    def apply_monthly_result(self, month: str) -> dict[str, Any]: ...
