from __future__ import annotations

from typing import Any, Protocol


class CategorizationRepositoryPort(Protocol):
    def list_categories(self) -> list[dict[str, Any]]: ...

    def create_category(self, slug: str, name: str) -> dict[str, Any]: ...

    def list_transactions(self, limit: int, offset: int, query: str, category_slug: str, review_status: str, sort_field: str, sort_direction: str) -> dict[str, Any]: ...

    def list_merchants(self, query: str, limit: int) -> list[dict[str, Any]]: ...

    def categorize(self, transaction_id: int, category_slug: str, scope: str, merchant_name: str | None) -> bool: ...

    def merge_alias(self, alias_hash: str, merchant_id: str) -> bool: ...

    def set_recurrence(self, transaction_id: int, mode: str, end_month: str | None) -> bool: ...

    def monthly_totals(self, months: int, include_card: bool, include_manual: bool, include_actual: bool, include_projected: bool, include_expense_income: bool) -> dict[str, Any]: ...

    def monthly_breakdown(self, month: str) -> dict[str, Any]: ...
