from __future__ import annotations

from typing import Any, Protocol


class RepositoryConflict(RuntimeError):
    pass


class InvoiceRepositoryPort(Protocol):
    def create(self, invoice_id: str, name: str, filename: str, pdf_path: str, reference_date: str) -> None: ...

    def list_all(self) -> list[dict[str, Any]]: ...

    def stats(self) -> dict[str, int]: ...

    def begin_processing(self, invoice_id: str) -> dict[str, Any]: ...

    def finish_processing(self, invoice_id: str, version_number: int, json_path: str, content_hash: str, transaction_count: int, status: str) -> None: ...

    def fail_processing(self, invoice_id: str) -> None: ...

    def latest_version(self, invoice_id: str) -> dict[str, Any] | None: ...

    def approve_latest(self, invoice_id: str) -> None: ...

    def mark_imported(self, invoice_id: str, version_number: int, postgres_version_id: int) -> None: ...

    def mark_import_failed(self, invoice_id: str) -> None: ...
